### ISSUE TITLE
Support for on conflict clause

### ISSUE THREAD

**Issue by lorefnon** [alfateam/rdb#42]
Hello, thanks for creating this library. The API looks really great for TS.

Curious if you would be open to adding support for on conflict clause for insert. It is quite convenient for handling upsert. [Related docs](https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT) in postgres manual.

**Comment by lroal** [comment]
Hello, thanks for your feedback! It is highly appreciated.
Yes, upserts are probably something that needs to be there. I need to do some research first, because I want the feature to be available for the other databases as well (MySQL, MSSQL, SAP, SQLite). I guess not all of them have this built-in, so I need to figure out an alternative implementation for those.
Also, I need to decide whether to have a separate upsert method or use the existing insert method with an extra input option.

**Comment by lroal** [comment]
Maybe we can use the same concurrency interface as on saveChanges().
Like this:
```javascript
await db.order.insert({ id: 1, name: 'foo', }, { concurrency: 'skipOnConflict' });
await db.order.insert({ id: 1, name: 'foo', }, { concurrency: 'overwrite' });
```
In the saveChanges method, it is also possible to have concurrency at the column level. But this is something that can be postponed.

Yes, having an additional upsert method equivalent to the last statement above, would be practical.
It is important to provide a uniform api, but not at all costs. There are several postgres specific methods in the [core](https://github.com/alfateam/rdb/blob/master/docs/docs.md) that are not exposed to the typescript api - yet. (E.g. schema, transaction lock, session lock).

**Comment by lroal** [comment]
Mostly done with the postgres part.  
Also works with custom strategy on columns.
### Usage and tests
 https://github.com/alfateam/rdb/commit/22a3d74452ac12bf759f5c2a417367a75c8702db#diff-be67661a5f61c78c382159f32e9f20fc7a6174c210e44bd8b2f9012958317aa4R71-R214

### Todo
- sap, mysql, mssql, sqlite
- insertAndForget

**Comment by lroal** [comment]
Done - in master now
